# nixos-btw — the desktop workstation.
#
# Everything portable lives in ../../modules/nixos. What is left here is what
# genuinely does not transfer to another machine: the bootloader layout, the
# disks (hardware-configuration.nix), the specific GPU, the specific audio
# interface, the monitors, and one project-local service.
{ config, lib, pkgs, ... }:

{
  imports = [
    # Generated by nixos-generate-config on THIS machine. Never copy it to
    # another one — install.sh regenerates it per host.
    ./hardware-configuration.nix
    ../../modules/nixos
  ];

  my.username = "r3dg0d";

  networking.hostName = "nixos-btw";

  # ---- boot ----------------------------------------------------------------
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  time.timeZone = "America/Los_Angeles";

  # ---- GPU -----------------------------------------------------------------
  # RTX 4090. The open kernel module is the recommended one for RTX 40-series;
  # an older (pre-Turing) card would need `open = false`.
  hardware.nvidia.open = true;

  # ---- network -------------------------------------------------------------
  networking.firewall.allowedTCPPorts = [ 34785 53317 ]; # 53317: LocalSend
  networking.firewall.allowedUDPPorts = [ 53317 ]; # LocalSend discovery

  # Blackholed hosts (written into /etc/hosts).
  networking.extraHosts = ''
    0.0.0.0 paradise-s1.battleye.com
    0.0.0.0 test-s1.battleye.com
    0.0.0.0 paradiseenhanced-s1.battleye.com
  '';

  # ---- login-screen music --------------------------------------------------
  # The QML greeter can't play audio (no PipeWire/PulseAudio exists for the
  # pre-login `sddm` user, and Qt6 MediaPlayer has no ALSA fallback), so instead
  # we play sddmmusic.ogg straight to the sound card via ALSA while the greeter
  # is on screen, and stop the moment a session starts (before the user's
  # PipeWire grabs the device). Runs as root so it can open the ALSA device
  # without audio-group membership. Targets the Scarlett 2i2 — hence host-only.
  systemd.services.sddm-login-music = {
    description = "Play login-screen music via ALSA while the SDDM greeter is shown";
    wantedBy = [ "multi-user.target" ];
    after = [ "sound.target" ];
    path = [ pkgs.procps pkgs.mpv ];
    serviceConfig = {
      Type = "simple";
      Restart = "always";
      RestartSec = 5;
    };
    script = ''
      ogg=/run/current-system/sw/share/sddm/themes/ascii-city/sddmmusic.ogg
      dev="alsa/plughw:CARD=USB,DEV=0"   # Focusrite Scarlett 2i2 (card id "USB")
      mpvpid=""
      cleanup() { [ -n "$mpvpid" ] && kill "$mpvpid" 2>/dev/null || true; }
      trap cleanup EXIT
      while true; do
        # Match the greeter by process name (comm, truncated to 15 chars),
        # not cmdline — `pgrep -f` false-matches anything mentioning the string.
        if pgrep -x 'sddm-greeter-qt.?' >/dev/null 2>&1; then
          # greeter is on screen — ensure music is playing
          if [ -z "$mpvpid" ] || ! kill -0 "$mpvpid" 2>/dev/null; then
            mpv --no-video --no-terminal --really-quiet \
                --loop-file=inf --volume=60 \
                --audio-device="$dev" "$ogg" &
            mpvpid=$!
          fi
        else
          # logged in (or no greeter) — stop music, free the device
          if [ -n "$mpvpid" ] && kill -0 "$mpvpid" 2>/dev/null; then
            kill "$mpvpid" 2>/dev/null || true
          fi
          mpvpid=""
        fi
        # 1s poll: on login the greeter exits first, and we must release the
        # ALSA device before the user's PipeWire tries to claim it.
        sleep 1
      done
    '';
  };

  # ---- project-local service ----------------------------------------------
  # VanillaAmerica+ Discord bot. Runs out of a working copy under the user's
  # home rather than the nix store, so it only exists on this machine; the
  # token lives in that directory's .env, never in this repository.
  systemd.services.va-plus-discord-bot =
    let
      workdir = "${config.my.homeDirectory}/Projects/VA+ SMP/discordbot";
    in
    {
      description = "VanillaAmerica+ Discord Bot & Community Synchronizer";
      wantedBy = [ "multi-user.target" ];
      after = [ "network-online.target" ];
      wants = [ "network-online.target" ];
      path = [ pkgs.nodejs pkgs.git pkgs.bash pkgs.coreutils ];
      # Do not crash-loop on a machine where the checkout is absent.
      unitConfig.ConditionPathExists = "${workdir}/.env";
      serviceConfig = {
        Type = "simple";
        User = config.my.username;
        WorkingDirectory = workdir;
        EnvironmentFile = "${workdir}/.env";
        Restart = "always";
        RestartSec = 10;
      };
      script = ''
        exec ${pkgs.nodejs}/bin/node ./node_modules/tsx/dist/cli.mjs apps/bot/src/index.ts
      '';
    };

  system.stateVersion = "26.05";
}
